# Generated by Django 5.0.3 on 2024-03-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=100)),
                ('date_creation', models.DateField()),
                ('derniere_version', models.CharField(max_length=50)),
                ('site_web', models.URLField()),
            ],
        ),
    ]
